// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    wesdt_swap
    (
        recoverEsdt
        wrapEsdt
        unwrapEsdt
        unwrapEsdtToAddress
        getLockedEsdtBalance
        getWrappedEsdtTokenId
        getEsdtTokenId
        pause
        unpause
        isPaused
    )
}

elrond_wasm_node::wasm_empty_callback! {}
