// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    bridged_tokens_wrapper
    (
        addWrappedToken
        updateWrappedToken
        removeWrappedToken
        whitelistToken
        updateWhitelistedToken
        blacklistToken
        depositLiquidity
        wrapTokens
        unwrapToken
        getUniversalBridgedTokenIds
        getTokenLiquidity
        getChainSpecificToUniversalMapping
        getchainSpecificTokenIds
        pause
        unpause
        isPaused
    )
}

elrond_wasm_node::wasm_empty_callback! {}
