[package]
name = "wesdt-swap-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.wesdt-swap]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"

[dependencies.elrond-wasm-debug]
version = "0.38.0"
