// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           38
// Async Callback (empty):               1
// Total number of exported functions:  40

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    esdt_safe
    (
        setTransactionBatchStatus
        addRefundBatch
        createTransaction
        claimRefund
        getRefundAmounts
        setFeeEstimatorContractAddress
        setServiceFeeContractAddress
        setEthTxGasLimit
        setServiceFeePercentage
        setMaxServiceFee
        setDefaultPricePerGasUnit
        setTokenTicker
        calculateRequiredFee
        calculateServiceFee
        getFeeEstimatorContractAddress
        getServiceFeeContractAddress
        getDefaultPricePerGasUnit
        getEthTxGasLimit
        getServiceFeePercentage
        getMaxServiceFee
        distributeFees
        addTokenToWhitelist
        removeTokenFromWhitelist
        getAllKnownTokens
        getAccumulatedTransactionFees
        setMaxTxBatchSize
        setMaxTxBatchBlockDuration
        getCurrentTxBatch
        getFirstBatchAnyStatus
        getBatch
        getBatchStatus
        getFirstBatchId
        getLastBatchId
        setMaxBridgedAmount
        getMaxBridgedAmount
        pause
        unpause
        isPaused
    )
}

elrond_wasm_node::wasm_empty_callback! {}
