// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    multi_transfer_esdt
    (
        batchTransferEsdtToken
        getAndClearFirstRefundBatch
        setWrappingContractAddress
        setSwappingContractAddress
        getWrappingContractAddress
        getSwappingContractAddress
        setMaxTxBatchSize
        setMaxTxBatchBlockDuration
        getCurrentTxBatch
        getFirstBatchAnyStatus
        getBatch
        getBatchStatus
        getFirstBatchId
        getLastBatchId
        setMaxBridgedAmount
        getMaxBridgedAmount
    )
}

elrond_wasm_node::wasm_empty_callback! {}
