name: CI

on:
  push:
      branches:
        - main
  pull_request:
        branches: [ main ]

permissions:
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: ElrondNetwork/elrond-actions/.github/workflows/contracts.yml@v1
    with:
      rust-toolchain: nightly-2022-10-16
      vmtools-version: v1.4.60
      extra-build-args: --ignore-eei-checks
      pip-erdpy-args: erdpy==v4.0.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
