name: Deploy to AWS

on:
  push:
    branches: ["main", "production"]
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      environment: ${{ github.ref_name == 'production' && 'production' || 'sandbox' }}
      path: bridge
      service_name: multiversex-bridge
    secrets: inherit
